Fix: console header error
txalkan/syron.js pull request #1
Opened 2024-11-06 03:19 UTC by hamyhya

2024-11-06 22:20 UTC, txalkan commented
the package-lock should not be included, right? pls merge the last version of dev into yours

2024-11-06 23:51 UTC, txalkan requested changes
please remove the `package-lock` from this PR (unless there is a reason for it to be included?)

and ask for my review afterwards, thanks

2024-11-06 23:51 UTC, txalkan commented on package-lock.json
I meant to delete this file from the PR (not the codebase) - how to do this?

2024-11-07 06:36 UTC, hamyhya commented on package-lock.json
@txalkan I have revert the package lock using same as from dev, now if you load the different here should be not much change

2024-11-07 12:35 UTC, txalkan approved these changes

2024-11-07 12:39 UTC, merged